// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrvbzznszecsbzwkwmfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhydmJ6em5zemVjc2J6d2t3bWZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1Mjk0NjcsImV4cCI6MjA3NjEwNTQ2N30.ODKdrpj4r-F59qSoU0BDTl4rXNBAEZVqDNZb_t1Urvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});